//! Hidden `generate-docs` subcommand.
//!
//! Walks the clap [`Command`](clap::Command) tree at runtime and emits:
//!
//! * troff man pages (`<out>/man/atl.1`, `<out>/man/atl-jira.1`, ...)
//! * shell completion scripts (`<out>/completions/`)
//! * a single aggregated markdown reference (`<out>/reference/atl.md`)
//!
//! This lives at runtime (rather than in `build.rs`) so that the main crate
//! does not need a `[build-dependencies]` copy of the entire clap graph. The
//! command is marked `hide = true` so it does not clutter `atl --help`.

use std::fs::File;
use std::io::Write;

use camino::{Utf8Path, Utf8PathBuf};
use clap::{Command, CommandFactory};

use crate::cli::args::{Cli, GenerateDocsArgs};
use crate::io::IoStreams;

/// Entry point for `atl generate-docs`.
pub fn run(args: &GenerateDocsArgs, io: &mut IoStreams) -> anyhow::Result<()> {
    let out = &args.output_dir;
    let man_dir = out.join("man");
    let completions_dir = out.join("completions");
    let reference_dir = out.join("reference");

    std::fs::create_dir_all(man_dir.as_std_path())?;
    std::fs::create_dir_all(completions_dir.as_std_path())?;
    std::fs::create_dir_all(reference_dir.as_std_path())?;

    let mut cmd = Cli::command();
    // Finalize so subcommand help / versions are populated.
    cmd.build();

    write_man_pages(&cmd, &man_dir)?;
    write_completions(&mut cmd, &completions_dir)?;
    write_markdown(&cmd, &reference_dir)?;

    writeln!(io.stdout(), "Generated docs in {out}")?;
    Ok(())
}

/// Recursively emits one `.1` file per non-hidden subcommand.
fn write_man_pages(cmd: &Command, out_dir: &Utf8Path) -> anyhow::Result<()> {
    walk_for_man(cmd, &[], out_dir)
}

fn walk_for_man(cmd: &Command, ancestors: &[&str], out_dir: &Utf8Path) -> anyhow::Result<()> {
    if should_skip(cmd) {
        return Ok(());
    }

    // File name: joined with '-', e.g. atl-jira-search.1
    let mut parts: Vec<&str> = ancestors.to_vec();
    parts.push(cmd.get_name());
    let file_name = format!("{}.1", parts.join("-"));
    let file_path = out_dir.join(&file_name);

    let mut file = File::create(file_path.as_std_path())?;
    // `clap_mangen::Man::new` takes the command by value; clone so we can
    // keep walking.
    let man = clap_mangen::Man::new(cmd.clone());
    man.render(&mut file)?;

    let next_ancestors: Vec<&str> = parts;
    for sub in cmd.get_subcommands() {
        walk_for_man(sub, &next_ancestors, out_dir)?;
    }
    Ok(())
}

/// Whether a command node should be skipped in generated output.
///
/// Skips `#[command(hide = true)]` nodes and the synthetic `help`
/// subcommand that clap auto-injects at every level of the tree.
fn should_skip(cmd: &Command) -> bool {
    cmd.is_hide_set() || cmd.get_name() == "help"
}

/// Writes one completion file per supported shell.
fn write_completions(cmd: &mut Command, out_dir: &Utf8Path) -> anyhow::Result<()> {
    use clap_complete::Shell;

    let targets: &[(Shell, &str)] = &[
        (Shell::Bash, "atl.bash"),
        (Shell::Zsh, "_atl"),
        (Shell::Fish, "atl.fish"),
        (Shell::PowerShell, "_atl.ps1"),
        (Shell::Elvish, "atl.elv"),
    ];

    for (shell, file_name) in targets {
        let path = out_dir.join(file_name);
        let mut file = File::create(path.as_std_path())?;
        clap_complete::generate(*shell, cmd, "atl", &mut file);
    }
    Ok(())
}

/// Emits the single aggregated markdown reference.
fn write_markdown(cmd: &Command, out_dir: &Utf8Path) -> anyhow::Result<()> {
    let mut buf = String::new();
    buf.push_str("# atl command reference\n\n");
    buf.push_str(
        "This file is generated by `scripts/gen-docs.sh` from the clap command tree. \
         Do not edit by hand.\n\n",
    );

    render_markdown(cmd, &[], 2, &mut buf);

    let path: Utf8PathBuf = out_dir.join("atl.md");
    let mut file = File::create(path.as_std_path())?;
    file.write_all(buf.as_bytes())?;
    Ok(())
}

/// Recursively renders a command and its non-hidden descendants into `out`.
fn render_markdown(cmd: &Command, ancestors: &[&str], heading_level: usize, out: &mut String) {
    if should_skip(cmd) {
        return;
    }

    let mut full_name_parts: Vec<&str> = ancestors.to_vec();
    full_name_parts.push(cmd.get_name());
    let full_name = full_name_parts.join(" ");

    let hashes = "#".repeat(heading_level.min(6));
    out.push_str(&format!("{hashes} {full_name}\n\n"));

    if let Some(about) = cmd.get_long_about().or_else(|| cmd.get_about()) {
        out.push_str(&format!("{about}\n\n"));
    }

    // Usage — clap's usage string is best-effort but good enough for ~80%
    // fidelity. We clone because `render_usage` takes `&mut self`.
    let usage = {
        let mut cloned = cmd.clone();
        cloned.build();
        cloned.render_usage().to_string()
    };
    if !usage.trim().is_empty() {
        out.push_str("**Usage**\n\n");
        out.push_str("```\n");
        out.push_str(usage.trim_end());
        out.push_str("\n```\n\n");
    }

    // Positional + flag arguments (skip the synthetic help/version).
    let args: Vec<_> = cmd
        .get_arguments()
        .filter(|a| !matches!(a.get_id().as_str(), "help" | "version"))
        .filter(|a| !a.is_hide_set())
        .collect();
    if !args.is_empty() {
        out.push_str("**Options**\n\n");
        for arg in args {
            let mut line = String::from("- `");
            if let Some(long) = arg.get_long() {
                line.push_str("--");
                line.push_str(long);
                if let Some(short) = arg.get_short() {
                    line.push_str(&format!(", -{short}"));
                }
            } else if let Some(short) = arg.get_short() {
                line.push_str(&format!("-{short}"));
            } else {
                // Positional argument — render its value name or id.
                let value_name = arg
                    .get_value_names()
                    .and_then(|names| names.first().cloned())
                    .map(|s| s.to_string())
                    .unwrap_or_else(|| arg.get_id().as_str().to_ascii_uppercase());
                line.push_str(&format!("<{value_name}>"));
            }
            line.push('`');
            if let Some(help) = arg.get_help() {
                line.push_str(&format!(" — {help}"));
            } else if let Some(help) = arg.get_long_help() {
                line.push_str(&format!(" — {help}"));
            }
            line.push('\n');
            out.push_str(&line);
        }
        out.push('\n');
    }

    let subs: Vec<&Command> = cmd.get_subcommands().filter(|s| !should_skip(s)).collect();
    if !subs.is_empty() {
        out.push_str("**Subcommands**\n\n");
        for sub in &subs {
            let name = sub.get_name();
            let about = sub.get_about().map(|s| s.to_string()).unwrap_or_default();
            if about.is_empty() {
                out.push_str(&format!("- `{name}`\n"));
            } else {
                out.push_str(&format!("- `{name}` — {about}\n"));
            }
        }
        out.push('\n');

        let next_ancestors: Vec<&str> = full_name_parts.clone();
        for sub in subs {
            render_markdown(sub, &next_ancestors, (heading_level + 1).min(6), out);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    fn make_args(path: &std::path::Path) -> GenerateDocsArgs {
        GenerateDocsArgs {
            output_dir: Utf8PathBuf::from_path_buf(path.to_path_buf())
                .expect("temp path is valid UTF-8"),
        }
    }

    #[test]
    fn generate_docs_creates_expected_structure() {
        let dir = tempdir().unwrap();
        let args = make_args(dir.path());
        let mut io = IoStreams::test();

        run(&args, &mut io).expect("generate-docs should succeed");

        let out = dir.path();

        let man = out.join("man/atl.1");
        assert!(man.exists(), "man/atl.1 missing");
        assert!(
            std::fs::metadata(&man).unwrap().len() > 0,
            "man/atl.1 is empty"
        );

        let bash = out.join("completions/atl.bash");
        assert!(bash.exists(), "completions/atl.bash missing");
        assert!(
            std::fs::metadata(&bash).unwrap().len() > 0,
            "completions/atl.bash is empty"
        );

        let zsh = out.join("completions/_atl");
        assert!(zsh.exists(), "completions/_atl missing");

        let fish = out.join("completions/atl.fish");
        assert!(fish.exists(), "completions/atl.fish missing");

        let ps = out.join("completions/_atl.ps1");
        assert!(ps.exists(), "completions/_atl.ps1 missing");

        let elv = out.join("completions/atl.elv");
        assert!(elv.exists(), "completions/atl.elv missing");

        let md = out.join("reference/atl.md");
        assert!(md.exists(), "reference/atl.md missing");
        let md_contents = std::fs::read_to_string(&md).unwrap();
        assert!(md_contents.contains("# atl command reference"));
        assert!(md_contents.contains("atl"));
    }

    #[test]
    fn generate_docs_skips_hidden_subcommands() {
        let dir = tempdir().unwrap();
        let args = make_args(dir.path());
        let mut io = IoStreams::test();
        run(&args, &mut io).unwrap();

        let hidden_man = dir.path().join("man/atl-generate-docs.1");
        assert!(
            !hidden_man.exists(),
            "hidden subcommand must not produce a man page"
        );

        let md = std::fs::read_to_string(dir.path().join("reference/atl.md")).unwrap();
        assert!(
            !md.contains("atl generate-docs"),
            "hidden subcommand leaked into markdown reference"
        );
    }

    #[test]
    fn generate_docs_is_idempotent() {
        let dir = tempdir().unwrap();
        let args = make_args(dir.path());
        let mut io = IoStreams::test();

        run(&args, &mut io).unwrap();
        run(&args, &mut io).unwrap();

        assert!(dir.path().join("man/atl.1").exists());
        assert!(dir.path().join("completions/atl.bash").exists());
        assert!(dir.path().join("reference/atl.md").exists());
    }
}
